sort_order = [
    "config",
    "tmux",
    "zoxide", 
]

[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --color=always {}"


[[session]]
name = "home"
path = "~"
startup_command = "figlet -f slant hvpaiva | lolcat"
preview_command = "eza --all --git --color=always {}"

[[session]]
name = "config"
path = "~/.config"
startup_command = "n $(ls -A | fzf)"
preview_command = "eza --all --git --color=always {}"

